language: objective-c
xcode_sdk: 7.1
notifications:
  email: true
  slack:
  #  secure: E1at9Fi4d2eLagKInwGOfvvcSr8rrVti+N3HzvlcL9UcYavwzfAstMX/nXoHTl8LR5/Dh4Sdja2+NeJp2uVNwlK7aVKk5egQ8q6qAEmcXlWgjqyyTusB1lgiaOQnbOuqsntg/3X5sP8nz5+V3sggelPnOrVwNCCkVXXSff2SHhE=
    secure: CgrupOVSqZhKxtOACPk9KVOjzfhpCg17NTGUQ4+YXMGjb0O3Ru3Zs9Sb6Mp30tR36nBFkMWWOSZkONPDB9WxPG6x/qlL2B9WoCaypuLBjzX3DaWRHYQ+z049yq0xKFHSnOry4bIzr+vhtzvnWLnC94OLuiRNChM4cEATA1T55T0=
rvm:
- 2.1.1
branches:
  only:
  - master
  - "/with\\-ci$/"
  - travis-ci
git:
  submodules: false


#- "./ci/installers/install-sauce-connect.sh"
#- "./ci/before_script_extra.sh"
#- "ulimit -n 8000"
# disabling sauce-connect until travis ichef issue is sorted
# - "./ci/start-sauce-connect.sh"
script:
#- "./ci/script.sh"
#- bash -c 'while true; do ping ondemand.saucelabs.com &> /dev/null; sleep 10; done' &
- ./ci/update_appium_io.sh
